name: CI/CD Pipeline for Microservice

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t roffidaijoubu/microservice-livechat:latest .
          docker push roffidaijoubu/microservice-livechat:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DOMAIN: ${{ secrets.DOMAIN }}
          TRAEFIK_ACME_EMAIL: ${{ secrets.TRAEFIK_ACME_EMAIL }}
        run: |
          # Set up SSH private key for GitHub Actions
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add host key verification
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          # Create temporary directory and prepare destination
          ssh $VPS_USER@$VPS_HOST "
            mkdir -p ~/temp_deploy &&
            sudo rm -rf /var/www/microservice-livechat &&
            sudo mkdir -p /var/www/microservice-livechat &&
            sudo mkdir -p /var/www/microservice-livechat/letsencrypt &&
            sudo chown -R 1000:1000 /var/www/microservice-livechat/letsencrypt
          "
          
          # Create and copy environment file to temp directory
          echo "DOMAIN=${DOMAIN}" > .env
          echo "TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL}" >> .env
          
          # Copy files to temporary directory
          scp .env docker-compose.yml $VPS_USER@$VPS_HOST:~/temp_deploy/
          
          # Move files and deploy
          ssh $VPS_USER@$VPS_HOST "
            sudo cp -r ~/temp_deploy/* /var/www/microservice-livechat/ &&
            rm -rf ~/temp_deploy &&
            cd /var/www/microservice-livechat &&
            sudo docker-compose down || true &&
            sudo docker-compose pull &&
            sudo docker-compose up -d
          "
