name: CI/CD Pipeline for Microservice

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t roffidaijoubu/microservice-livechat:latest .
          docker push roffidaijoubu/microservice-livechat:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          # Set up SSH private key for GitHub Actions
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add host key verification
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          # Create temporary directory and prepare destination
          ssh $VPS_USER@$VPS_HOST "
            mkdir -p ~/temp_deploy &&
            sudo rm -rf /var/www/microservice-livechat &&
            sudo mkdir -p /var/www/microservice-livechat
          "
          
          # Copy files to temporary directory
          scp docker-compose.yml $VPS_USER@$VPS_HOST:~/temp_deploy/
          scp .env $VPS_USER@$VPS_HOST:~/temp_deploy/ || true

          # Move files to final destination and deploy
          ssh $VPS_USER@$VPS_HOST "
            sudo cp ~/temp_deploy/* /var/www/microservice-livechat/ &&
            rm -rf ~/temp_deploy &&
            
            # Create network if it doesn't exist
            sudo docker network inspect web >/dev/null 2>&1 || sudo docker network create web &&
            
            # Deploy using docker-compose
            cd /var/www/microservice-livechat &&
            sudo docker-compose down || true &&
            sudo docker-compose pull &&
            sudo docker-compose up -d
          "
