name: CI/CD Pipeline for Microservice

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t roffidaijoubu/microservice-livechat:latest .
          docker push roffidaijoubu/microservice-livechat:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DOMAIN: ${{ secrets.DOMAIN }}
          TRAEFIK_ACME_EMAIL: ${{ secrets.TRAEFIK_ACME_EMAIL }}
        run: |
          # Set up SSH private key for GitHub Actions
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add host key verification
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          # Create and copy environment file first
          echo "DOMAIN=${DOMAIN}" > .env
          echo "TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL}" >> .env
          
          # Create directories and set permissions
          ssh $VPS_USER@$VPS_HOST "
            sudo mkdir -p /var/www/microservice-livechat/letsencrypt &&
            sudo chown -R 1000:1000 /var/www/microservice-livechat/letsencrypt
          "
          
          # Copy files
          scp .env docker-compose.yml $VPS_USER@$VPS_HOST:/var/www/microservice-livechat/
          
          # Deploy
          ssh $VPS_USER@$VPS_HOST "
            cd /var/www/microservice-livechat &&
            sudo docker-compose down || true &&
            sudo docker-compose pull &&
            sudo docker-compose up -d
          "
