name: CI/CD Pipeline for Microservice

on:
  push:
    branches:
      - main  # Trigger the pipeline when pushing to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t roffidaijoubu/microservice-livechat:latest .
          docker push roffidaijoubu/microservice-livechat:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Deploy to VPS
      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Set up SSH private key for GitHub Actions
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Ensure the Docker 'web' network exists
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "
            sudo docker network inspect web >/dev/null 2>&1 || sudo docker network create web
          "

          # Pull the latest repository and update docker-compose
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "
            cd /var/www/microservice-livechat || (sudo mkdir -p /var/www/microservice-livechat && cd /var/www/microservice-livechat) &&
            sudo git init &&
            sudo git remote set-url origin https://ghp_${PAT_TOKEN}@github.com/roffidaijoubu/microservice-livechat.git || sudo git remote add origin https://ghp_${PAT_TOKEN}@github.com/roffidaijoubu/microservice-livechat.git &&
            sudo git config --global credential.helper store &&
            echo "https://ghp_${PAT_TOKEN}@github.com" > ~/.git-credentials &&
            sudo git fetch origin &&
            sudo git reset --hard origin/main
          "

          # Deploy the microservice using docker-compose
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "
            cd /var/www/microservice-livechat &&
            sudo docker-compose down &&
            sudo docker-compose up -d
          "

      # Step 2: Make sure the new image is running
      - name: Make sure the new image is running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/microservice-livechat
            docker-compose down
            docker-compose pull
            docker-compose up -d
